### ISSUE TITLE
Documenting data

### ISSUE THREAD

**Issue by MikkoVihtakari** [davidcsterratt/RImageJROI#9]
One thing we are still lacking is documenting data. I found out that documenting it is rather easy in roxygen2 (http://adv-r.had.co.nz/Documenting-functions.html), but takes some time to get done. One should make an R script for data and write something like following:
# ' A roi file of type 'line'
# '
# ' Write something here. It becomes description
# '
# ' This line should become details
# ' @docType data
# ' @format write here too
# ' @name line.roi
# ' @usage how to use the data

NULL

The down side is that this has to be done for each file.

**Comment by davidcsterratt** [comment]
I'm wondering if we need to document the data after all, as it's there for test purposes, and not a `data` directory (which is, I think, intended for packages supplying data to be used by the user rather than for test or examples). I'm closing the issue for now, but feel free to reopen if you think we do need to document the data.
